// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/results/{job_id}": {
            "get": {
                "description": "Returns analysis results for a completed job, including tool outputs and APK metadata",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get job results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job UUID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResultsResponse"
                        }
                    },
                    "400": {
                        "description": "invalid job_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "job not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "job not complete",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/results/{job_id}/file": {
            "get": {
                "description": "Returns the contents of a file within the job's output directory. Files larger than 100 KB are truncated; the X-Truncated: true header is set in that case.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Retrieve a file from job output",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job UUID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Relative file path within the output directory",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File contents",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid job_id or path",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "file not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/results/{job_id}/search": {
            "get": {
                "description": "Performs a substring search across .java, .smali, .xml, and .json files in the job's output directory",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Search within job output files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job UUID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search query string",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of results (default 50, max 200)",
                        "name": "max",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "invalid job_id or missing query",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/results/{job_id}/tree": {
            "get": {
                "description": "Lists files and subdirectories under the job's output directory at the given relative path",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "List directory tree",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job UUID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Relative path within the output directory",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TreeResponse"
                        }
                    },
                    "400": {
                        "description": "invalid job_id or path",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "path not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/status/{job_id}": {
            "get": {
                "description": "Returns the current status of an analysis job",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job UUID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "invalid job_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "job not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.MetaInfo": {
            "type": "object",
            "properties": {
                "activities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "min_sdk": {
                    "type": "integer"
                },
                "package_name": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "receivers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "target_sdk": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                },
                "version_code": {
                    "type": "integer"
                }
            }
        },
        "api.MobSFInfo": {
            "type": "object",
            "properties": {
                "report": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "api.ResultsResponse": {
            "type": "object",
            "properties": {
                "apktool": {
                    "$ref": "#/definitions/api.ToolInfo"
                },
                "jadx": {
                    "$ref": "#/definitions/api.ToolInfo"
                },
                "job_id": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/api.MetaInfo"
                },
                "mobsf": {
                    "$ref": "#/definitions/api.MobSFInfo"
                },
                "package_name": {
                    "type": "string"
                },
                "results_path": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.SearchMatch": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "file": {
                    "type": "string"
                },
                "line": {
                    "type": "integer"
                }
            }
        },
        "api.SearchResponse": {
            "type": "object",
            "properties": {
                "matches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SearchMatch"
                    }
                },
                "query": {
                    "type": "string"
                },
                "truncated": {
                    "type": "boolean"
                }
            }
        },
        "api.StatusResponse": {
            "type": "object",
            "properties": {
                "apktool_status": {
                    "type": "string"
                },
                "completed_at": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "jadx_status": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "mobsf_status": {
                    "type": "string"
                },
                "package_name": {
                    "type": "string"
                },
                "results_path": {
                    "type": "string"
                },
                "sha256": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.ToolInfo": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.TreeEntry": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.TreeResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.TreeEntry"
                    }
                },
                "path": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "coordinator.apps.blj.wtf",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Android RE Pipeline — Coordinator API",
	Description:      "Tracks analysis jobs and serves decompiled APK results.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
